import type { Metadata } from 'next';
import { Cormorant } from 'next/font/google';

import DiscountPlate from '@/components/discount-plate';
import ErrorBoundary from '@/components/error-boundary';
import Footer from '@/components/footer';
import Header from '@/components/header';
import { offerText } from '@/constants/offers';

import StyledComponentsRegistry from './registry';

import './globals.css';

const cormorant = Cormorant({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <StyledComponentsRegistry>
          <ErrorBoundary>
            <Header />
            <DiscountPlate description={offerText} />
            {children}
            <Footer />
          </ErrorBoundary>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
