import type { Metadata } from 'next';
import { Cormorant } from 'next/font/google';

import DiscountPlate from '@/components/discount-plate';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { offerText } from '@/constants/offers';

import './globals.css';

const cormorant = Cormorant({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <Header />
        <DiscountPlate description={offerText} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
